name: Build 🔨

on:
  push:
    tags:
      - '*'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library #Path where Unity stocks build cache
          key: Library
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: 2020.1.10f1
      # Build
      - name: Build project for Windows
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2020.1.10f1
          targetPlatform: StandaloneWindows64 
      # Output 
      - uses: actions/upload-artifact@v2
        with:
          name: Build #We store the .exe as "Build"
          path: build
      - name: Zip build
        run: |
          pushd build/StandaloneWindows64
          zip -r ../../StandaloneWindows64.zip .
          popd
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: StandaloneWindows64.zip
          name: Release ${{ github.ref }}
