name: Test ⚙

on:
  pull_request: {}
  push: { branches: [master, develop] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Test Unity Project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library #Path where Unity stocks build cache
          key: Library
      # Test
      - name: Build & run unite tests
        uses: game-ci/unity-test-runner@v2.0-alpha-5
        with:
          unityVersion: 2020.1.10f1
